apiVersion: v1
appVersion: v1.0.3-rc
description: ssi-abstraction deployment
name: ssi-abstraction
version: 1.0.3
icon: "https://www.vereign.com/wp-content/themes/vereign2020/images/vereign-logo.svg"
