apiVersion: v1
appVersion: v1.0.7-rc
description: connection-manager deployment
name: connection-manager
version: 1.0.7
icon: "https://www.vereign.com/wp-content/themes/vereign2020/images/vereign-logo.svg"
